# Generated by Django 4.1.5 on 2023-03-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippens', '0002_place_tour_delete_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trippens.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addon',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trippens.place'),
            preserve_default=False,
        ),
    ]
