# Generated by Django 4.1.5 on 2023-02-17 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0002_branches_delete_branch'),
        ('user_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_requirments.branches'),
        ),
    ]
