# Generated by Django 4.1.5 on 2023-02-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0002_alter_customuser_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Mobile Number'),
        ),
    ]
