# Generated by Django 4.1.5 on 2023-02-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0003_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_logout',
            field=models.DateTimeField(null=True),
        ),
    ]
