# Generated by Django 4.1.5 on 2023-02-17 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0002_branches_delete_branch'),
        ('user_managment', '0004_alter_customuser_last_logout'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_requirments.branches')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('is_created', models.DateField(auto_now_add=True)),
                ('is_updated', models.DateField(null=True)),
                ('updated_to', models.DateField(null=True)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField(null=True)),
                ('whatsapp', models.CharField(max_length=12, verbose_name='Whatsapp Number')),
                ('city', models.CharField(max_length=50, null=True)),
                ('pax', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('vehicle', models.CharField(max_length=50, null=True)),
                ('progress', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50, null=True)),
                ('remarks', models.TextField(null=True)),
                ('StaffBranch', models.ManyToManyField(related_name='customers', to='user_managment.staffbranch')),
            ],
        ),
    ]
