# Generated by Django 4.1.5 on 2023-02-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0002_branches_delete_branch'),
        ('user_managment', '0005_staffbranch_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='StaffBranch',
        ),
        migrations.AddField(
            model_name='customers',
            name='branch',
            field=models.ManyToManyField(related_name='customers', to='admin_requirments.branches'),
        ),
    ]
