# Generated by Django 4.1.5 on 2023-02-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0002_branches_delete_branch'),
        ('user_managment', '0007_customers_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='branch',
        ),
        migrations.AddField(
            model_name='customers',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_requirments.branches'),
        ),
    ]
