# Generated by Django 4.1.5 on 2023-02-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0008_remove_customers_branch_customers_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
