# Generated by Django 4.1.5 on 2023-02-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0009_alter_customers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='vehicle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
