# Generated by Django 4.1.5 on 2023-02-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0012_alter_assignedcustomer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_managment.customers'),
        ),
    ]
