# Generated by Django 4.1.5 on 2023-02-24 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0002_branches_delete_branch'),
        ('user_managment', '0013_alter_assignedcustomer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='adhar_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_requirments.branches'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_requirments.designation'),
        ),
    ]
