# Generated by Django 4.1.5 on 2023-02-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0014_alter_customuser_adhar_no_alter_customuser_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
