# Generated by Django 4.1.5 on 2023-02-24 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0015_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcustomer',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_managment.customuser'),
        ),
        migrations.AlterField(
            model_name='staffbranch',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_managment.customuser'),
        ),
    ]
