# Generated by Django 4.1.5 on 2023-02-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0016_alter_assignedcustomer_staff_alter_staffbranch_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='staffbranch',
            name='Branches',
        ),
        migrations.RemoveField(
            model_name='staffbranch',
            name='staff',
        ),
        migrations.DeleteModel(
            name='AssignedCustomer',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='StaffBranch',
        ),
    ]
