# Generated by Django 4.1.5 on 2023-02-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0019_customers_is_asigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcustomer',
            name='asigned_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assignedcustomer',
            name='response',
            field=models.TextField(max_length=200),
        ),
    ]
