# Generated by Django 4.1.5 on 2023-03-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0021_remove_customers_tour_customers_tours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='is_updated',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
    ]
