# Generated by Django 4.1.5 on 2023-03-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0022_alter_customers_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='is_updated',
            field=models.DateField(null=True),
        ),
    ]
