# Generated by Django 4.1.5 on 2023-03-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0024_alter_customers_is_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='is_updated',
        ),
    ]
