# Generated by Django 4.1.5 on 2023-03-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0028_alter_customers_updated_to_alter_leaverequest_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='updated_to',
            field=models.DateField(null=True),
        ),
    ]
