# Generated by Django 4.1.5 on 2023-03-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0031_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='followup_time',
            field=models.TimeField(),
            preserve_default=False,
        ),
    ]
