# Generated by Django 4.1.5 on 2023-03-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0032_response_followup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='category',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='progress',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='remarks',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='type',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=12, verbose_name='Whatsapp Number'),
        ),
    ]
