# Generated by Django 4.1.5 on 2023-03-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0034_rename_response_customerresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedcustomer',
            name='response',
        ),
        migrations.AddField(
            model_name='assignedcustomer',
            name='attented',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
