# Generated by Django 4.1.5 on 2023-03-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0035_remove_assignedcustomer_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcustomer',
            name='attented',
            field=models.BooleanField(default=False),
        ),
    ]
