# Generated by Django 4.1.5 on 2023-03-28 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0036_alter_assignedcustomer_attented'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_managment.customerresponse')),
            ],
        ),
    ]
