# Generated by Django 4.1.5 on 2023-02-24 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0002_branches_delete_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True)),
                ('adhar_no', models.CharField(blank=True, max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/staff_images/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/staff_credentials/')),
                ('last_logout', models.DateTimeField(null=True)),
                ('branch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_requirments.branches')),
                ('designation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_requirments.designation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
