# Generated by Django 4.1.5 on 2023-02-24 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0003_userstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstaff',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userstaff',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_requirments.branches'),
        ),
        migrations.AlterField(
            model_name='userstaff',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_requirments.designation'),
        ),
    ]
