# Generated by Django 4.1.5 on 2023-02-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0004_alter_userstaff_address_alter_userstaff_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstaff',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
