# Generated by Django 4.1.5 on 2023-02-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0005_userstaff_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstaff',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
