# Generated by Django 4.1.5 on 2023-03-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippens', '0001_initial'),
        ('admin_requirments', '0006_rename_phone_number_userstaff_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trippens.trippenstour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trippens.trippenstour'),
            preserve_default=False,
        ),
    ]
