# Generated by Django 4.1.5 on 2023-03-20 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0033_alter_customers_address_alter_customers_category_and_more'),
        ('admin_requirments', '0008_alter_userstaff_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateField()),
                ('days_count', models.IntegerField()),
                ('night_count', models.IntegerField()),
                ('adult_count', models.IntegerField()),
                ('child_count', models.IntegerField()),
                ('pick_up', models.CharField(max_length=100)),
                ('drop_off', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, max_length=200)),
                ('include', models.TextField(blank=True, max_length=200)),
                ('exclude', models.TextField(blank=True, max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_managment.customers')),
                ('rooms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_requirments.rooms')),
                ('vehicles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_requirments.vehicle')),
            ],
        ),
    ]
