# Generated by Django 4.1.5 on 2023-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0009_tourform'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourform',
            name='expired_at',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
