# Generated by Django 4.1.5 on 2023-03-20 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trippens', '0005_alter_activity_price_alter_addon_price'),
        ('admin_requirments', '0010_tourform_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourform',
            name='child_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CustomInetenary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('activivty', models.ManyToManyField(blank=True, related_name='customInetenary', to='trippens.activity')),
                ('addon', models.ManyToManyField(blank=True, related_name='customInetenary', to='trippens.addon')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_requirments.tourform')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trippens.place')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trippens.trippenstour')),
            ],
        ),
    ]
