# Generated by Django 4.1.5 on 2023-04-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0012_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='date',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
