# Generated by Django 4.1.5 on 2023-04-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0013_accounts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_veryfied',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
