# Generated by Django 4.1.5 on 2023-04-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0014_accounts_is_veryfied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='total',
            field=models.FloatField(),
        ),
    ]
