# Generated by Django 4.1.5 on 2023-04-03 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0037_audio'),
        ('admin_requirments', '0015_alter_accounts_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(blank=True, max_length=100)),
                ('Advance', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookedTours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(default='Pending', max_length=100)),
                ('total', models.FloatField(blank=True)),
                ('accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_requirments.accounts')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_managment.customers')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trans', models.ManyToManyField(blank=True, related_name='BookedTours', to='admin_requirments.transacions')),
            ],
        ),
    ]
