# Generated by Django 4.1.5 on 2023-04-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0016_transacions_bookedtours'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacions',
            name='date',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
