# Generated by Django 4.1.5 on 2023-04-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0017_transacions_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedtours',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='transacions',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
