# Generated by Django 4.1.5 on 2023-04-04 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0018_remove_bookedtours_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedtours',
            name='trans',
        ),
        migrations.AddField(
            model_name='transacions',
            name='bookedtours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_requirments.bookedtours'),
        ),
    ]
