# Generated by Django 4.1.5 on 2023-04-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_requirments', '0019_remove_bookedtours_trans_transacions_bookedtours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='offer',
            field=models.FloatField(default=0),
        ),
    ]
